# NumPy
* 배열 자료형을 제공하지 않는 파이썬에서 배열을 구현한 표준 패키지
* 수치해석용 패키지
* 다차원 배열 자료구조 클래스인 `ndarray` 클래스 지원
* 벡터, 행렬을 사용하는 선형대수 계산에 주로 사용

#### 장점
* C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
* 벡터화 연산(vectorized operation)을 이용해 간단한 코드로도 복잡한 선형 대수 연산 수행 가능
* 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용해 간단한 코드로도 복잡한 수식 계산 가능

In [ ]:
import numpy as np

# 1. 1차원 배열 만들기

##### array()
매개변수로 list를 넣어 Numpy 배열 ndarray를 만든다.

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

> 배열 객체와 리스트 객체 차이
  * 리스트 클래스 객체
      * 각각의 원소가 다른 자료형이 될 수 있다.
  * 배열 클래스 객체
      * 배열처럼 연속적인 메모리 배치이여서 모든 원소가 같은 자료형이어야 한다.
      * 그 대신 원소에 대한 접근과 반목문 실행이 빨라진다.

# 2. 벡터화 연산
* 배열 객체는 벡터화 연산(vectorized operation)을 지원한다.
> 벡터화 연산
    * 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리

* 벡터화 연산을 사용하여 for 반복문 없이 한번에 연산 가능
    * 계산 속도도 반복문 사용시 보다 훨씬 빠름

In [4]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer = []
for di in data:
    answer.append(2 * di)
    
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

#### 벡터화 연산을 사용한 연산

In [7]:
x = np.array(data)
print(2 * x)

[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

2 * a + b

array([12, 24, 36])

In [11]:
a == 2

array([False,  True, False])

In [12]:
b > 10

array([False,  True,  True])

In [13]:
(a == 2) & (b > 10)

array([False,  True, False])

참고) 일반 list 객체에 정수를 곱하여 객체의 크기가 정수배 만큼 증가한다.

In [9]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# 3. 2차원 배열 만들기
* ndarray(N-dimensional Array)는 다차원 배열 자료 구조를 제공한다.
* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성 가능
* 안쪽 리스트 길이 : 행렬의 열 수(가로 크기)
* 바깥쪽 리스트 길이 : 행렬의 행 수(세로 크기)

##### 2차원 배열

In [15]:
# 2 * 3 array
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

##### 행의 수

In [16]:
len(c)

2

##### 열의 수

In [17]:
len(c[0])

3

# 4. 3차원 배열 만들기
* 리스트의 리스트의 리스트를 이용
* 크기를 나타낼 때 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이 순서로 표시

##### 3차원 배열

In [18]:
# 2 * 3 * 4 array
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

##### 행, 열, 깊이

In [19]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

# 5. 배열 차원, 크기 알아내기

##### ndim
배열의 차원
##### shape
배열의 크기

In [24]:
a = np.array([1, 2, 3])

print(a.ndim)
print(a.shape)

1
(3,)


In [25]:
c = np.array([[0, 1, 2], [3, 4, 5]])

print(c.ndim)
print(c.shape)

2
(2, 3)


In [26]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

print(d.ndim)
print(d.shape)

3
(2, 3, 4)


# 6. 배열의 인덱싱

## 6.1. 1차원 배열 인덱싱
리스트의 인덱싱과 같다.

In [29]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


## 6.2. 다차원 배열 인덱싱
콤마(,)로 접근 가능. (,)로 구분된 차원을 axis(축)이라고도 한다.

In [32]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0, -1]

2

## 6.3. 팬시 인덱싱(fancy indexing)
인덱싱이라는 이름이 붙었지만, 사실 DB의 query(질의) 기능
### 6.3.1. boolean 배열 인덱싱
인덱스 배열의 크기가 ndarray 객체의 크기와 같아야 한다.

In [41]:
# 짝수인 원소 골라내기

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 인덱스 배열
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [42]:
# 조건문 연산을 통한 간단한 인덱스 배열

a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [43]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [47]:
# 다차원 배열
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

### 6.3.2. 정수 배열 인덱싱
인덱스 배열의 원소 각각이 원래 ndarray 객체의 원소 하나를 가리키는 인덱스 정수이어야 한다.

In [44]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 7])
a[idx]

array([11, 33, 55, 77, 88])

이 때는 배열 크기가 달라도 상관없다.

In [46]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [48]:
# 다차원 배열
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

# 7. 배열 슬라이싱
다차원 배열의 원소 중 복수 개에 접근

In [34]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0, :]

array([0, 1, 2])

In [35]:
a[:, 1]

array([1, 4])

In [36]:
a[1, 1:]

array([4, 5])

In [37]:
a[:2, :2]

array([[0, 1],
       [3, 4]])