In [2]:
import numpy as np

# 1. 벡터화 연산
* 벡터화 연산을 쓰면 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복 연산 가능
* 선형 대수 공식과 동일한 아주 간단한 파이썬 코드 작성 가능

#### 벡터화 연산을 사용하지 않은 사칙 연산

In [6]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

%time # cell 코드의 실행시간을 측정하는 IPython 매직 명령
z = np.zeros_like(x)

for i in range(10000):
    z[i] = x[i] + y[i]
    
# 자료상 5.84ms 걸림 (성능이 좋아져서 그런가)

Wall time: 0 ns


In [4]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

#### 벡터화 사칙 연산

In [8]:
# 덧셈 연산 하나로 끝난다.
# 연산 속도가 훨씬 빠르다.
%time
z = x + y
z[:10]

Wall time: 0 ns


array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

#### 논리 연산
사칙 연산뿐 아니라 비교 연산 같은 논리 연산도 벡터화 연산 가능

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

a == b

array([False,  True, False,  True])

##### all
각 원소들 일일히 비교가 아닌 모든 원소 그룹지어서 연산

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.all(a == b)

False

In [12]:
np.all(a == c)

True

#### 지수 함수, 로그 함수 등의 수학 함수
수학 함수도 벡터화 연산을 지원한다.

In [14]:
a = np.arange(5)
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [16]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

# 2. 스칼라와 벡터/행렬 곱셉

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [19]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 3. 브로드캐스팅(broadcasting)
서로 다른 크기의 두 배열의 사칙 연산이 가능하게 하는 기능
* 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법  

#### 벡터 + 스칼라 연산 브로드캐스팅 동작 원리

In [21]:
# 벡터 x
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [24]:
# 스칼라 1
y = np.ones_like(x) # 스칼라 1을 벡터 x와 같은 크기로 확장
y

array([1, 1, 1, 1, 1])

In [25]:
x + y

array([1, 2, 3, 4, 5])

#### 브로드캐스팅 결과

In [26]:
x + 1 # 위와 결과 동일

array([1, 2, 3, 4, 5])

#### 더 높은 차원에서의 브로드캐스팅

In [33]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [34]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [36]:
y2 = np.arange(3)
y2

array([0, 1, 2])

In [37]:
x + y2

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

# 3. 차원 축소 연산
행렬의 한 축의 원소들을 하나의 데이터 집합으로 보고 그 집합의 통계 수치 등을 연산하여 차원 축소(dimension reduction)하는 연산
* 지원하는 차원 축소 연산 명령 혹은 메서드 
    * 최대/최소 : `min`, `max`, `argmin`, `argmax`
    * 통계 : `sum`, `mean`, `median`, `std`, `var`
    * 논리 : `all`, `any`

In [40]:
x = np.array([1, 3, 2, 4])
x

array([1, 3, 2, 4])

In [41]:
np.sum(x)

10

In [43]:
np.min(x)

1

In [44]:
x.argmax() # 최대값의 위치

3

In [47]:
np.all([True, True, False])

False

In [51]:
np.any([True, True, False])

True

In [52]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [53]:
np.any(a != 0)

False

In [54]:
np.any(a == a)

True

In [56]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

연산 대상이 2차원인 경우 `axis` 인수로 어느 차원으로 계산할지 지시한다.
* `axis=0` : 열 연산 (디폴트)
* `axis=1` : 행 연산

In [57]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [63]:
x.sum()

6

In [62]:
x.sum(axis=0) # 열 합계

array([3, 3])

In [61]:
x.sum(axis=1) # 행 합계

array([2, 4])

# 4. 정렬
##### sort
원소를 크기순 정렬
* 2차원 이상인 경우 `axis` 인수로 정렬할 축 결정
* `axis=0` : 각각의 행 따로따로 정렬
* `axis=1` : 각각의 열 따로따로 정렬
* `aixs=-1` : 가장 안쪽(나중) 차원 정렬(디폴트)

In [65]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
np.sort(a) # axis=-1 또는 1과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [66]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

sort() 메서드는 in-place 메서드(해당 객체의 자료 자체가 변경되는)이므로 주의

In [67]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

##### argsort
정렬하지 않고 순서만 알고 싶을 때
* 크기순으로 정렬될 데이터의 인덱스 반환

In [68]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [69]:
a[j]

array([12, 25, 38, 42])

In [70]:
np.sort(a)

array([12, 25, 38, 42])